# Generated by Django 4.1.7 on 2023-04-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0002_id_anonymous'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ID',
        ),
        migrations.RemoveField(
            model_name='anonymous',
            name='user_number',
        ),
    ]
