# Generated by Django 4.1.7 on 2023-04-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0004_post_dislikes_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
