# Generated by Django 4.1.7 on 2023-04-09 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0005_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_code', models.TextField()),
                ('user_receiver_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='anonymous.anonymous')),
                ('user_sender_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='anonymous.anonymous')),
            ],
        ),
    ]
