# Generated by Django 4.1.7 on 2023-04-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0007_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
