# Generated by Django 4.1.7 on 2023-08-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0009_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='user_receiver_request',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='user_sender_request',
        ),
    ]
