# Generated by Django 4.1.7 on 2023-08-16 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0013_comments_dislikes_comments_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anonymous.messages'),
        ),
    ]
