# Generated by Django 4.1.7 on 2023-08-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0015_remove_chat_messages_messages_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='chat',
        ),
    ]
