# Generated by Django 4.1.7 on 2023-08-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0018_postinteraction_remove_messages_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinteraction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anonymous.anonymous'),
        ),
    ]
