# Generated by Django 4.1.7 on 2023-08-23 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0022_alter_postinteraction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinteraction',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction', to='anonymous.post'),
        ),
    ]
