# Generated by Django 4.1.7 on 2023-08-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0023_alter_postinteraction_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
